server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/catalog/**, /api/v1/products/**, /api/v1/categories/**
        - id: pricing-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/pricing/**, /api/v1/coupons/**
        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/cart/**
        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/orders/**
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/payments/**
        - id: inventory-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/inventory/**
        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/notifications/**
        - id: review-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/reviews/**
        - id: admin-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/admin/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
